/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    BannerCarousel: typeof import('./components/common/BannerCarousel.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    Footer: typeof import('./components/layout/footer.vue')['default']
    Header: typeof import('./components/layout/header.vue')['default']
    LogoSearch: typeof import('./components/layout/logoSearch.vue')['default']
    PageContainer: typeof import('./components/layout/pageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/common/sidebar.vue')['default']
    SideNavigation: typeof import('./components/layout/SideNavigation.vue')['default']
    Swiper: typeof import('./components/common/swiper.vue')['default']
    'Swiper copy': typeof import('./components/common/swiper copy.vue')['default']
  }
}
